requires "Mojo";
requires "IO::Socket::Socks";
requires "EV";
requires "Cpanel::JSON::XS";
requires "Net::DNS::Native";
requires "IO::Socket::SSL";
requires "Role::Tiny";
requires "Future::AsyncAwait";
requires "WWW::Wappalyzer";
